<?php

namespace AppBundle\Repository;

/**
 * SitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitesRepository extends \Doctrine\ORM\EntityRepository {
}
