<?php

namespace AppBundle\Repository;

/**
 * TagsExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsExtraRepository extends \Doctrine\ORM\EntityRepository {
}
