<?php

namespace AppBundle\Repository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends \Doctrine\ORM\EntityRepository
{
}
