<?php

namespace AppBundle\Repository;

/**
 * TagsAnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsAnnoncesRepository extends \Doctrine\ORM\EntityRepository
{

  /**
   * @param $idAnnonces
   *
   * @return mixed
   */
  public function findAnnonces($idAnnonces) {
    $qb = $this->createQueryBuilder('a');
    $qb->where("a.idAnnonce IN(:ids)");
    $qb->setParameter('ids', $idAnnonces);
    $query = $qb->getQuery();
    return $query->execute();
  }


  /**
   * @param $params
   * @param $ids_count
   *
   * @return mixed
   */
  public function filterAnnonces($params, $ids_count) {
    $qb = $this->createQueryBuilder('a');
    $qb->where("a.idAnnonce IN(:ids)");
    //$qb->setParameter('ids', array_values($ids_count));

    foreach($params as $key => $param) {
      $qb->andWhere("a.Value = (:param)");
      $qb->setParameter('param', $param);
    }
    $query = $qb->getQuery();
    return $query->execute();
  }

}
