<?php

namespace AppBundle\Repository;

/**
 * TagsAnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsAnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
}
